CREATE TABLE IF NOT EXISTS STATIC_COMMIT_PROCESSED (
  REPO TEXT,
  COMMIT TEXT,
  STATUS TEXT,
  BUILD TEXT,
  BUILD_LOG TEXT,
  CREATED timestamp DEFAULT NOW(),
  MODIFIED timestamp DEFAULT NOW(),
  PRIMARY KEY (REPO, COMMIT));

CREATE TABLE IF NOT EXISTS STATIC_COMMIT_LINE_WARNING (
  REPO TEXT,
  COMMIT TEXT,
  RESOURCE TEXT, -- resource
  LINE TEXT,
  SFP TEXT,
  CWE TEXT,
  VALID TEXT DEFAULT NULL,
  TRUST TEXT DEFAULT NULL,
  GENERATOR_TOOL TEXT,
  WEAKNESS TEXT,
  CREATED timestamp DEFAULT NOW());