CREATE TABLE IF NOT EXISTS STATIC_COMMIT_LINE_BLAME (
  REPO TEXT,
  COMMIT TEXT,
  RESOURCE TEXT, -- resource
  LINE INT,
  ORIGIN_COMMIT TEXT,
  ORIGIN_RESOURCE TEXT,
  ORIGIN_LINE INT,
  IS_NEW_LINE BOOL, -- redundant as commit == ORIGIN_commit
  PRIMARY KEY (REPO, COMMIT, RESOURCE));